### PR TITLE
Integrate with SQLite/SQL Server Compact Toolbox

### PR DESCRIPTION
**Pull request by bricelam**
@ErikEJ I was thinking about how these might integrate, and one idea was to show an **Install SQLite Toolbox** command when users right-click on the connection in Server Explorer.

Once installed, it could show additional commands like **New Query**, **Edit Top 200 Rows**, and **Script as CREATE** that users would expect to find. The commands would essentially just invoke yours.

I'm still not even sure how this extension will ship, it might only ever be a small part of the EF Core Power Tools to light up the table selection dialog during reverse engineer...

### CODE REVIEW

**Comment by ErikEJ** [comment]
That looks like a feasible approach, to avoid too much duplication of effort.

Just FYI, the SQLite Toolbox itself does not use DDEX for storing connections, it just uses an embedded database.
Also, the SQLite Toolbox is heavily tied to System.Data.SQLite, which it includes,

What would be great initially would be the ability to offer this VSIX for EF Core Power Tools as an alternative to the horrible, and error prone exercise of installing the System.Data.SQLite ADO.NET provider in GAC, combined with my "Simple DDEX" provider - or simply include this as part of EF Core Power Tools (Microsoft.Data.Sqlite + the DDEX provider).

I tried installing the VSIX, but it looks like I need an update to Microsoft.Data.Sqlite to make it work. (Invalid connection string whne trying to save a connection)

**Comment by ErikEJ** [comment]
>> EF Core Power Tools to light up the table selection dialog during reverse engineer...

I am actually using the EF Core provider to get the list of tables/views from databases (via DatabaseModel), so I only use DDEX to store and list the connection information (Database provider type, connection display name and connection string).

I am considering using just Credential store and a custom dialog for that https://github.com/ErikEJ/EFCorePowerTools/issues/288#issuecomment-744195935

**Comment by ErikEJ** [comment]
Notice that SQLite Toolbox already has an icon in the Server Explorer:

image

**Comment by bricelam** [comment]
Yeah, I think there are probably better ways to address this scenario. I'm worried about users stumbling across my extension and not knowing about your more capable one. But, like you said in https://github.com/bricelam/VS.Data.Sqlite/issues/5#issuecomment-1185216067, it would probably be best to state what it's for and not for in the README with a recommendation to use your extension instead if you need any of the "What it's not for" features.

**Pull request closed without merging**
