### PR TITLE
Prevent clicking OK until the database file exists

### LINKED ISSUE #30: "Test" button always works
It just creates a new empty (0 byte) database file in a random location if you enter just a database name with no path

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #30

(Test still passes though, but Data Connection cannot be saved)

### CODE REVIEW

**Comment by ErikEJ** [comment]
@bricelam Thoughts?

**Comment by bricelam** [comment]
Hmm... It's by design that an empty Data Source creates a temporary, on-disk database. This is SQLite's native behavior.

I can also imagine creating a connection string to a database that does not yet exist.

But maybe, given the current use cases, it would be more valuable to verify that the database exists, and is not temporary...

**Comment by ErikEJ** [comment]
>> But maybe, given the current use cases, it would be more valuable to verify that the database exists, and is not temporary..

Yes, that was my thoughts.

**Comment by bricelam** [comment]
@ErikEJ Do you think implementing a better **Test Connection** (but still allowing less useful connection strings) would be sufficient? Something like this...

```cs
class SqliteConnectionUITester : IVsDataConnectionUITester
{
    public void Test(IVsDataConnectionUIProperties connectionUIProperties)
    {
        var connectionOptions = new SqliteConnectionStringBuilder(connectionUIProperties.ToString());

        if (connectionOptions.DataSource.Length == 0)
        {
            throw new Exception("A temporary on-disk database will be created.");
        }

        if (connectionOptions.DataSource == ":memory:"
            || connectionOptions.Mode == SqliteOpenMode.Memory)
        {
            throw new Exception("A temporary in-memory database will be created.");
        }

        // Throw 'unable to open database file' when the file doesn't exist
        connectionOptions.Mode = SqliteOpenMode.ReadOnly;

        using var connection = new SqliteConnection(connectionOptions.ToString());
        connection.Open();
    }
}
```

image

**Comment by ErikEJ** [comment]
Ah - for sure. Never found that interface.

**Comment by bricelam** [comment]
lol, I had to do *a lot* of digging. Cool, I'll push a fix

**Pull request closed without merging**
